server:
  port: 80
  servlet:
    context-path: /
  ssl:
    enabled: false

thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    
npmon:
  iperf: iperf3
  ethr: ethr
    
simpleconfig:
  role: slave
  target: 140.92.24.29
  iperfport: 5201
  ethrport: 8888
  nport: 80
  twoways: true

# In properties file
# TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
  level:
    org:
      apache: WARN
      springframework: WARN
#       iii:
#         npmon:
#           endpoint: INFO

# appender:
#   console:
#     layout:
#       pattern: %m%n
